name: result
description: Result Monad to handle errors in Dart.
repository: https://github.com/hugo-pcl/result
version: 2.0.0

publish_to: https://git.wyatt-studio.fr/api/packages/hugo/pub

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  stack_trace: ^1.11.0

dev_dependencies:
  melos: ^3.0.1
  test: ^1.24.2
  wyatt_analysis:
    hosted: https://git.wyatt-studio.fr/api/packages/Wyatt-FOSS/pub
    version: ^2.5.0
