name: result
description: A std::result like object to handle error.
repository: https://github.com/hugo-pcl/result
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  stack_trace: ^1.11.0

dev_dependencies:
  melos: ^3.0.1
  test: ^1.24.2
  wyatt_analysis:
    hosted: https://git.wyatt-studio.fr/api/packages/Wyatt-FOSS/pub
    version: ^2.5.0
