name: sealed_result
description: Implementation of the Result object which allows to handle errors easily using sealed classes.
repository: https://github.com/hugo-pcl/result
version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  stack_trace: ^1.11.0

dev_dependencies:
  melos: ^3.0.1
  test: ^1.24.3
